Add possibility for set test Parameters when queued tests
HCK-CI/toolsHCK pull request #25
Opened 2024-06-27 08:13 UTC by Jedoku

2024-06-29 05:40 UTC, akihikodaki requested changes
Use `hashtable` instead of inventing another syntax and parsing it.

2024-07-01 20:30 UTC, kostyanf14 requested changes

2024-07-01 20:30 UTC, kostyanf14 commented on toolsHCK.ps1
> +        [Parameter(Position=6)][String]$parameters
the `parameter` is not a mandatory option. In help should be `[-parameters <parameters>]`.

2024-07-01 20:30 UTC, kostyanf14 commented on toolsHCK.ps1
> +        [Switch]$help,
Please split into 2 commit: refactoring of param list and adding new parameters

2024-07-01 20:30 UTC, kostyanf14 commented on toolsHCK.ps1
> +        Write-Output ""
what if the value should be `my=password`?

2024-07-04 08:07 UTC, akihikodaki approved these changes

2024-07-04 08:11 UTC, kostyanf14 approved these changes

2024-07-04 08:11 UTC, merged